
<footer>
	<div class="row">
<div class="column">
	<div class="footer-links">
		<a href="javascript:;">Connect</a>
		<a href="javascript:;">Socialize</a>
		<a href="">Integrate</a>
	</div>
	

</div>
<div class="column">
	<div class="footer-links">
		<a href="javascript:;">External Links</a>
		<a href="javascript:;">Multimedia</a>
		<a href="javascript:;">Approach</a>
	</div>
	

</div>
<div class="column">
	<div class="footer-links">
		<a href="javascript:;">Facebook</a>
		<a href="javascript:;">Twitter</a>
		<a href="javascript:;">Google+</a>

	</div>
	

</div>
</div>
<!-- <div id="footer">
	<a href="#" id="android" class="fa fa-android"></a>
  <a href="#" id="facebook" class="fa fa-facebook"></a>
  <a href="#" id="twitter" class="fa fa-twitter"></a>
  <a href="#" id="instagram" class="fa fa-instagram"></a>
  <a href="#" id="youtube" class="fa fa-youtube"></a>
  <a href="#" id="google" class="fa fa-google"></a>
	
</div> -->
<p>Event Scheduling Software  | Developed By <strong>Umah Chukwudi</strong></p>
</footer>
<!-- <button id="goUpButton" class="fa fa-arrow-up" title="Navigate To Top"><button> -->
	<img src="assets/images/interface/up21.png" id="goUpButton" title="Navigate To Top" >
</div>

</body> 
 <script src="assets/js/jquery-3.2.1.min.js"></script>
 <script src="assets/js/valid-date.js"></script>
 <script src="assets/js/init.js"></script>
 
 


</html> 