<div class="slideshow-container">

<div class="mySlides fade">
  <div class="numbertext">How Do I Manage My <br>Tight Work Schedule?</div>
  <img src="assets/images/img_nature_wide.jpg" style="width:100%">
  <div class="text">We've Got You Covered</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">Efficiently and Effortlessly <br>Create Social Events Schedule</div>
  <img src="assets/images/img_fjords_wide.jpg" style="width:100%">
  <div class="text">SEMS Helps You Become Productive</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">Perform CRUD Operations<br> On the Database</div>
  <img src="assets/images/img_mountains_wide.jpg" style="width:100%">
  <div class="text">Welcome to the Future of Event Scheduling!</div>
</div>

<a class="prev" >&#10094;</a>
<a class="next">&#10095;</a>

</div>
<br>

<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span> 
</div>